#!/usr/bin/env bash
# SPDX-License-Identifier: LGPL-2.1-or-later

# Adapted from APT's JSON hooks test:
# https://salsa.debian.org/apt-team/apt/-/blob/3a7aecd232dfdbcec5dbdc3af16e03479d47d917/test/integration/test-apt-cli-json-hooks#L22

while true; do
    read REQUEST <&$APT_HOOK_SOCKET
    read EMPTY <&$APT_HOOK_SOCKET

    # Hello handshake
    if echo "$REQUEST" | grep -q "\.hello"; then
        printf '{"jsonrpc": "2.0", "result": {"version": "0.1"}, "id": 0}\n\n' >&$APT_HOOK_SOCKET
    fi

    # Update systemd-boot version installed in EFI system partition if systemd is updated
    # n.b. far from robust notification parsing logic...
    if echo "$REQUEST" | grep '\.install\.post' | grep '\"mode\"\s*:\s*\"install\"' | grep -q '\"name\"\s*:\s*\"systemd\"'; then
        if command -v bootctl >/dev/null 2>&1; then
            bootctl update
        fi
    fi

    # Bye notification
    if echo "$REQUEST" | grep -q "\.bye"; then
        exit 0;
    fi
done
